website/recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('recipes/', views.MealListView.as_view(), name='meal_list'),
    path('recipes/<int:pk>/', views.MealDetailView.as_view(), name='meal_details'),
    path('fridge/', views.IngredientListView.as_view(), name='fridge'),
    path('basket/', views.BasketView.as_view(), name='basket'),
    path('api/fridge/add/<str:user_uuid>', views.add_ingredient_to_fridge),
    path('api/fridge/remove/<str:user_uuid>', views.add_ingredient_to_fridge),
    path('api/fridge/list/<str:user_uuid>', views.add_ingredient_to_fridge),
    path('api/users/new', views.create_user)
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('', RedirectView.as_view(pattern_name='recipes:meal_list'))
]

website/recipes/models.py
from django.db import models


class Meal(models.Model):
    """Represents a meal recipe."""
    name = models.CharField(max_length=100)
    instructions = models.TextField()
    image_url = models.URLField(max_length=200, null=True, blank=True)
    small_image_url = models.URLField(max_length=200, null=True, blank=True)
    video_instructions_url = models.URLField(max_length=200, null=True, blank=True)

    @property
    def youtube_embed_url(self) -> str | None:
        try:
            return self.video_instructions_url.replace('watch?v=', 'embed/')
        except AttributeError:
            return None

    def __str__(self):
        return self.name


class IngredientCategory(models.Model):
    """Represents an ingredient category"""
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    """Represents an ingredient"""
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)
    image_url = models.URLField(max_length=200, null=True, blank=True)
    small_image_url = models.URLField(max_length=200, null=True, blank=True)
    meals = models.ManyToManyField(Meal, through='MealIngredientMeasure')
    category = models.ForeignKey(IngredientCategory, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name


class MealIngredientMeasure(models.Model):
    """An ingredient measure for a specific meal"""

    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    measure = models.CharField(max_length=100)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['meal', 'ingredient'], name='unique_meal_ingredient_measure')
        ]

    def __str__(self):
        return f'"{self.ingredient}" in "{self.meal}": {self.measure}'


class TheMealDBMeal(models.Model):
    """Stores the meal's id at TheMealDB"""

    themealdb_id = models.PositiveBigIntegerField(primary_key=True)
    meal = models.OneToOneField(Meal, on_delete=models.CASCADE)


class TheMealDBIngredient(models.Model):
    """Stores the ingredient's id at TheMealDB"""

    themealdb_id = models.PositiveBigIntegerField(primary_key=True)
    ingredient = models.OneToOneField(Ingredient, on_delete=models.CASCADE)


class TheMealDBIngredientCategory(models.Model):
    """Stores the ingredient category's name at TheMealDB"""

    temealdb_name = models.CharField(max_length=30, primary_key=True)
    category = models.OneToOneField(IngredientCategory, on_delete=models.CASCADE)


class User(models.Model):
    uuid = models.UUIDField(primary_key=True)
    created_at = models.DateTimeField(auto_now=True)


class Fridge(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ingredients = models.ManyToManyField(Ingredient)


class Basket(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    meals = models.ManyToManyField(Meal)


# Implementing MySQL fulltext search lookup.
# Code taken from: https://docs.djangoproject.com/en/stable/releases/1.10/#search-lookup-replacement
class Search(models.Lookup):  # noqa
    lookup_name = 'search'

    def as_mysql(self, compiler, connection):
        lhs, lhs_params = self.process_lhs(compiler, connection)
        rhs, rhs_params = self.process_rhs(compiler, connection)
        params = lhs_params + rhs_params
        return 'MATCH (%s) AGAINST (%s IN BOOLEAN MODE)' % (lhs, rhs), params


models.CharField.register_lookup(Search)
models.TextField.register_lookup(Search)

website/recipes/views.py
import json
import uuid

from django.http import HttpRequest, JsonResponse, Http404
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView

from .models import Meal, MealIngredientMeasure, Ingredient, User, Fridge, Basket
from .utils import serializers


class MealListView(ListView):
    model = Meal
    paginate_by = 50

    def get_queryset(self):
        meal_queryset = Meal.objects

        # Filtering search results, if query is present.
        if search_query := self.request.GET.get('q'):
            meal_queryset = meal_queryset.filter(name__search=search_query)
        if ingredients := self.request.GET.get('require'):
            ingredients = json.loads(ingredients)
            meal_queryset = meal_queryset.filter(mealingredientmeasure__ingredient__id__in=ingredients)

        return meal_queryset.order_by('name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Default value for search_query
        context['search_query'] = ''

        # Setting search query from query parameter, if query is present.
        if search_query := self.request.GET.get('q'):
            context['search_query'] = search_query

        return context


class MealDetailView(DetailView):
    model = Meal

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Adding MealIngredientMeasure list for the meal
        context['measures'] = MealIngredientMeasure.objects.filter(meal=context['meal'])

        return context


class IngredientListView(ListView):
    model = Ingredient
    ordering = ['-category', 'name']


class BasketView(TemplateView):
    template_name = 'recipes/basket.html'


def get_meal_json(request: HttpRequest, meal_id: int):
    """Responses with json-serialized meal. Look at
    serializers.serialize_meal doc for schema info"""
    meal = get_object_or_404(Meal, pk=meal_id)
    ingredient_measures = MealIngredientMeasure.objects.filter(meal=meal).all()

    serialized_meal = serializers.serialize_meal(meal, ingredient_measures)
    return JsonResponse(serialized_meal)


def create_user(request: HttpRequest):
    user = User(uuid=uuid.uuid4())
    user.fridge = Fridge()
    user.basket = Basket()
    user.save()
    return JsonResponse({'user_id': user.uuid})


def add_ingredient_to_fridge(request: HttpRequest, user_uuid: str):
    if request.method != 'POST':
        raise Http404
    fridge = get_object_or_404(Fridge, user_id=user_uuid)
    data = json.loads(request.body)
    ingredient_id = data['ingredient_id']
    if fridge.ingredients.filter(pk=ingredient_id).exists():
        return JsonResponse({'success': False})
    ingredient = get_object_or_404(Ingredient, pk=ingredient_id)
    fridge.ingredients.add(ingredient)
    fridge.save()
    return JsonResponse({'success': True})


def remove_ingredient_from_fridge(request: HttpRequest, user_uuid: str):
    if request.method != 'POST':
        raise Http404
    fridge = get_object_or_404(Fridge, user_id=user_uuid)
    data = json.loads(request.body)
    ingredient_id = data['ingredient_id']
    if not fridge.ingredients.filter(pk=ingredient_id).exists():
        return JsonResponse({'success': False})
    ingredient = get_object_or_404(Ingredient, pk=ingredient_id)
    fridge.ingredients.remove(ingredient)
    fridge.save()
    return JsonResponse({'success': True})


def list_ingredients_at_fridge(request: HttpRequest, user_uuid: str):
    fridge = get_object_or_404(Fridge, user_id=user_uuid)
    ingredients = fridge.objects.all()
    ingredients = [ingredient.id for ingredient in ingredients]
    return JsonResponse({'ingredients': ingredients})

website/recipes/templates/recipes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.cdnfonts.com/css/ink-free" rel="stylesheet">
    <link href="{% static 'recipes/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'recipes/css/unique.css' %}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'recipes/images/siteIcon.ico' %}">
    <script src="{% static 'recipes/js/api.js' %}"></script>
    <script src="{% static 'recipes/js/main.js' %}"></script>
    <title>{% block title %}MyMealList{% endblock %}</title>

    {% block additionalHeadElements %}{% endblock %}
</head>
<body style="background-color:#f2f2f0;">
<div class="container-fluid unique-color-1" style="border-radius: 0.275rem">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom-0">
        <p class="d-flex align-items-center mb-3 mb-md-0 me-md-auto ms-md-4 text-dark">
            <span class="fs-3 text-family-header">MyMealList</span>
        </p>

        <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'recipes:meal_list' %}"
                                    class="nav-link text-black text-family-header fs-5 button-header-text">Dishes</a></li>
            <li class="nav-item"><a href="{% url 'recipes:fridge' %}"
                                    class="nav-link text-black text-family-header fs-5 button-header-text">Fridge</a></li>
        </ul>
    </header>
</div>

<div id="content" class="container mt-4 px-lg-5" style="min-height: 800px">
    {% block content %}{% endblock %}
</div>

<footer class="mt-4 unique-color-1">
    <div class="container py-4 align-items-center">
        <hr class="horizontal-hr">
        <p class="text-center" style="font-size: 0.9rem;">
            Developers' contacts:
        </p>
        <p class="text-center" style="font-size: 0.8rem;">
            trotsenko.ant07@gmail.com
            <br>
            swan.polina00@gmail.com
            <br>
            olgacherry03@gmail.com
        </p>

    </div>

</footer>


<script src="{% static 'recipes/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

website/recipes/templates/recipes/ingredient_list.html
{% extends 'recipes/base.html' %}
{% load static %}
{% block content %}
    <h1 class="text-center mt-5 fw-bold text-fingredient_idamily-header mb-4" style="font-size: 24px;">Current
        products</h1>

    <div class="container-fluid">
        <div id="current" class="row mt-2 underImageText">
        </div>
    </div>

    <div class="container border-top mt-5">

        <div class="container">
            <button type="button" class="button-cook" onclick="redirectToQuery({% url 'recipes:meal_list' %})">What can I cook?</button>
        </div>
        
        <h1 class="text-center mt-5 fw-bold text-family-header mb-4" style="font-size: 24px;">All ingredients</h1>
    </div>
    {% regroup ingredient_list by category as ingredient_groups %}
    {% static 'recipes/images/noImage.jpg' as no_image_url %}
    {% for category, ingredients in ingredient_groups %}
        <div class="category">
            <h2 class="text-center mt-4 fw-bold text-family-header mb-4"
                style="font-size: 22px;">{{ category.name|default:"Other" }}</h2>
            <div class="container-fluid">
                <div class="row mt-2 underImageText">
                    {% for ingredient in ingredients %}
                        <div class="col text-center ingredient_{{ ingredient.id }}">
                            <p class="text-center mb-1">{{ ingredient.name }}</p>
                            {% firstof ingredient.small_image_url ingredient.image_url no_image_url as image_url %}
                            <img src="{{ image_url }}" alt="{{ ingredient.name }} image"
                                 class="rounded mx-auto d-block mb-2" style="width: 60px; height: 60px;">
                            <button type="button"
                                    class="mini-button-add-remove mb-4 ingredientButton_{{ ingredient.id }}">+
                            </button>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endfor %}

    <script src="{% static "recipes/js/fridge.js" %}"></script>
{% endblock %}

website/recipes/templates/recipes/meal_detail.html
{% extends 'recipes/base.html' %}
{% load static %}

{% block content %}

    <p class="text-center text-family-header fs-3 mt-2">{{ meal.name }}</p>

    <div class="row mt-4">
        <div class="col">
            <img src="{% if meal.image_url %}
                {{ meal.image_url }}
            {% else %}
                {% static 'recipes/images/noImage.jpg' %}
            {% endif %}" alt="{{ meal.name }} image" class="rounded mx-auto d-block mt-4" width="350px" height="350px">
        </div>

        <div class="col" style="min-width: 200px;">
            <p class="text-center mt-4 fw-bold" style="font-size: 17px;">Ingredients:</p>
            <div class="container d-flex justify-content-center">
                <ul class="list-group ms-2">
                    {% for measure in measures %}
                        <li class="mt-2">{{ measure.ingredient }} — {{ measure.measure }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <p class="text-center mt-5 fw-bold" style="font-size: 17px;">Recipe:</p>
        <p class="mt-2 fs-6">{{ meal.instructions }}</p>
    </div>

    {% if meal.youtube_embed_url %}
        <div class="container mb-5 mt-5">
            <div style="display: flex; align-items: center; justify-content: center;">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="{{ meal.youtube_embed_url }}"></iframe>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

website/recipes/templates/recipes/meal_list.html
{% extends 'recipes/base.html' %}
{% load static %}

{% block content %}
    <form action="{% url 'recipes:meal_list' %}" method="get">
        <div class="input-group rounded">
            <input name="q" type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
                   aria-describedby="search-addon" value="{{ search_query }}"/>
            <span class="input-group-text border-0 unique-color-2" id="search-addon" width="25px" height="25px">
              <img src="{% static 'recipes/images/search.png' %}" alt="Search icon" width="18px" height="18px"
                   class="unique-color-2"/>
            </span>
        </div>
    </form>

    <div class="container mt-5">
        <div class="row mt-2 underImageText">
            {% for meal in page_obj %}
                <div class="col">
                    <a href="{% url 'recipes:meal_details' pk=meal.pk %}">
                        <img src="{% if meal.small_image_url %}
                            {{ meal.small_image_url }}
                        {% elif meal.image_url %}
                            {{ meal.image_url }}
                        {% else %}
                            {% static 'recipes/images/noImage.jpg' %}
                        {% endif %}" alt="{{ meal.name }} icon" class="rounded mx-auto d-block dish-image" width="120px"
                             height="120px"/>
                    </a>
                    <a href="{% url 'recipes:meal_details' pk=meal.pk %}" class="text-decoration-none text-black">
                        <p class="text-center mt-2">{{ meal.name }}</p></a>
                </div>
            {% endfor %}
        </div>
    </div>

    <nav aria-label="..." class="mt-3">
        <ul class="pagination justify-content-center">
            {% if not page_obj.has_previous %}
                <li class="page-item disabled">
                    <a class="page-link" style="color: grey" href="#"
                       tabindex="-1">Previous</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" style="color: grey"
                       href="?page={{ page_obj.previous_page_number }}&q={{ search_query }}">Previous</a>
                </li>
            {% endif %}

            {% for page in page_obj.paginator.page_range %}
                <li class="page-item {% if page == page_obj.number %}active{% endif %}">
                    <a class="page-link" style="color: green"
                       href="?page={{ page }}&q={{ search_query }}">{{ page }}</a>
                </li>
            {% endfor %}

            {% if not page_obj.has_next %}
                <li class="page-item disabled">
                    <a class="page-link" style="color: grey" href="#"
                       tabindex="-1">Next</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" style="color: grey"
                       href="?page={{ page_obj.next_page_number }}&q={{ search_query }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}